name: Sync obsidian

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main # 监听主分支变化

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Clone private repo
        run: |
          git clone --depth=1 --filter=blob:none --sparse "https://${{ secrets.OBSIDIAN_SYNC_TOKEN }}@github.com/chanshiyucx/obsidian.git"
          cd obsidian
          git sparse-checkout set blog

      - name: Sync blog directory
        run: |
          rsync -av --delete obsidian/Blog/ ./posts/
          rsync -av --delete obsidian/Leetcode/ ./leetcode/
          rm -rf obsidian

      - name: Commit and push changes
        run: |
          git config user.name "chanshiyu"
          git config user.email "chanshiyucx@gmail.com"
          git add blog/
          git commit -m "Sync blog directory from obsidian" || echo "No changes to commit"
          git push
