name: sync from obsidian 

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the target repository
      - name: Checkout target repository (blog)
        uses: actions/checkout@v3

      # Step 2: Clone the private obsidian repository
      - name: Clone obsidian private repository
        run: |
          git clone --depth=1 --filter=blob:none --sparse "https://${{ secrets.OBSIDIAN_SYNC_TOKEN }}@github.com/chanshiyucx/obsidian.git" obsidian
          cd obsidian
          # 只检出 blog 和 Leetcode 目录
          git sparse-checkout set Blog Leetcode
          cd ..

      # Step 3: Sync obsidian/Blog to blog/posts
      - name: Sync Blog directory to blog/posts
        run: |
          rsync -av --delete obsidian/Blog/ ./posts/
          rm -f ./posts/SUMMARY.md

      # Step 4: Sync obsidian/Leetcode to blog/leetcode
      - name: Sync Leetcode directory to blog/leetcode
        run: |
          rsync -av --delete obsidian/Leetcode/ ./leetcode/
          rm -f ./leetcode/SUMMARY.md

      # Step 5: Sync obsidian/Album to blog/album
      - name: Sync Album directory to blog/album
        run: |
          rsync -av --delete obsidian/Album/ ./album/

      # Step 6: Commit and push changes to target repository
      - name: Commit and push changes
        run: |
          git config user.name "chanshiyu"
          git config user.email "chanshiyucx@gmail.com"
          git add .
          git commit -m "Sync Blog and Leetcode directories from obsidian repository" || echo "No changes to commit"
          git push
